version: '3'
services:
    my-app:
        build: './my-app'
        ports:
            - "8080:8080"
        #links: 
        #    - api
        #    - db
    api:  
        build: './api'
        ports:    
            - "7777:7777"
    db:
        image: mongo
        ports: 
            - "27017:27017"
