version: '3'
services:
    my-app:
        build: './my-app'
        ports:
            - "8080:80"
        #links: 
        #    - api
        #    - db
        
    api:  
        build: './api'
        ports:    
            - "7777:7777"
        
    db:
        build: './db'
        ports: 
            - "27017:27017"
